### ISSUE TITLE
15_basic_materials crashes on Android

### ISSUE THREAD

**Issue by Keenuts** [google/bigwheels#140]
The function CreateIBLTextureFromFile doesn't work on Android, as android cannot use fstream, and should go through the asset manager.

Issues: https://github.com/google/bigwheels/pull/117/files/14b03b6294feec086df7ef8db4fffe6f29ea530a#diff-d1e3258e70bf12dc8481423798d4de28900ca1e9b015bd1eebe3e1bd4e50d860R1158

**Comment by chaoticbob** [comment]
I have a fix. Waiting on a couple of other PRs before submitting it.
