### ISSUE TITLE
Require up-to-date to merge

### ISSUE THREAD

**Issue by Keenuts** [google/bigwheels#157]
Hello!

Merging #148 broke HEAD because the CI run before some other PR was merged, and this code "conflicted" with the other.
A solution to avoid those issues is to require up-to-date before merging.

This means we won't be able to merge multiple PRs at once, but makes merging safer.
Is anyone against this change?

**Comment by apazylbe** [comment]
My vote is in favour, we can always switch back if it turns out there are issues. I think it will give the option to "update branch" before merging, there is also a setting to "Always suggest updating pull request branches", but it might be unnecessary if we already require branches be up to date

**Comment by Keenuts** [comment]
Ah yes, nice to know this button exists!

**Comment by hysw** [comment]
I'm guessing also not merge PR that is not mark as auto-merged by the author?

Github is quite bad at managing stacked or branched PRs.
E.g. many of #132 's comment are for #136 , and they need to be merged in a specific sequence for diff to make sense.

**Comment by apazylbe** [comment]
That would only be possible for authors with write access, which right now is not everybody. The contributing page (https://github.com/google/bigwheels/blob/main/CONTRIBUTING.md#for-developers-contributing-a-patch) right now suggests that "it is the job of the reviewer to merge the PR", but maybe that can apply ifan author doesn't have write access.
I am good with "require up to date" and author will merge or enable auto merge if they have write access, otherwise reviewers will. I like the idea of "requiring up to date branches", regardless of who does the merge.

**Comment by Keenuts** [comment]
> I'm guessing also not merge PR that is not mark as auto-merged by the author?

As Aliya said, need write permissions, and if we need to check if the person has write permissions before merging, it seems bound to fail.

What about marking PRs you know need to be merged in a specific order as draft until condition is met? So the authors does the ordering bookkeeping, and maintainers don't have to remember that.

**Comment by Keenuts** [comment]
Seems like there is no additional push-back? Will enable the feature tomorrow if nothing new shows up here.

**Comment by hysw** [comment]
> What about marking PRs you know need to be merged in a specific order as draft until condition is met? So the authors does the ordering bookkeeping, and maintainers don't have to remember that.

Require up-to-date should solves most of those problems. PRs conflicting with each other does not necessarily have an ordering to them, so they are fine until the conflicting PR is submitted and they are not fine to submit anymore, but that depend on a different author to mark as draft, which is unrealistic, and we go back to require up-to-date to merge.
