### ISSUE TITLE
[benchmark] [graphics_pipeline] dx12 crashes on startup

### ISSUE THREAD

**Issue by angela28chen** [google/bigwheels#282]
Platform: Windows
NVIDIA Quadro P1000
Driver version: 30.0.15.1109

Description: `vk_graphics_pipeline.exe` runs fine but `dx12_graphics_pipeline.exe` appears to crash on startup

Error message:
```
*** PPX ASSERT ***
Message   : Descriptor binding type is not pushable in Direct3D 12
Condition : false
Function  : ppx::grfx::dx12::PipelineInterface::CreateApiObjects
Location  : C:\src\git\bigwheels\src\ppx\grfx\dx12\dx12_pipeline.cpp : 298

Assertion failed: false, file C:\src\git\bigwheels\src\ppx\grfx\dx12\dx12_pipeline.cpp, line 298
```

**Comment by chaoticbob** [comment]
D3D12 only supports pushable buffers.

**Comment by angela28chen** [comment]
If `dx12_graphics_pipeline.exe` is intentionally not working, then should we change it so that it's not built?

**Comment by chaoticbob** [comment]
Yes, that's a really good point. Sorry, it slipped my mind.
