### ISSUE TITLE
Change Geometry's buffer growth rate to reduce allocations

### ISSUE THREAD

**Issue by chaoticbob** [google/bigwheels#310]
The buffers in Geometry currently make a bunch of allocations whne appending data. If the buffer doesn't have a max element count, it should grow by 1.5x or 2x  the current capacity as opposed to the size of the element.

**Comment by apazylbe** [comment]
I believe this is done with https://github.com/google/bigwheels/pull/312 ?

**Comment by Keenuts** [comment]
Yes! Marking as done 😊
