### ISSUE TITLE
Consider removing debug capture swapchain for XR

### ISSUE THREAD

**Issue by apazylbe** [google/bigwheels#464]
Added in https://github.com/google/bigwheels/pull/11 

Given we can capture with tools (for ex RenderDoc) directly, I am not sure if we still need this. It also makes code more complicated. So if this is not needed anymore, we should remove this.

**Comment by apazylbe** [comment]
@wangra-google Thoughts? Do you think we still need this?

**Comment by wangra-google** [comment]
oh, sorry i totally missed this conversation. Yeah, I don't think this is needed anymore. Feel free to remove this.
