### ISSUE TITLE
Geometry death tests fail on some platforms

### ISSUE THREAD

**Issue by s-perron** [google/bigwheels#496]
The death tests added in https://github.com/google/bigwheels/pull/490 are failing because the string does not match correctly.

https://github.com/google/bigwheels/blob/8bb848be3cec90a1608efa0c452d5a65afc23a88/src/test/geometry_test.cpp#L71

Since the string does not change any real content, could we change it to `""` like all of the other death tests?

**Comment by footballhead** [comment]
Makes sense to me, the death the thing I'm testing (not the contents of the message).
