### ISSUE TITLE
support grfx::DESCRIPTOR_TYPE_STORAGE_BUFFER in DX11 and DX12

### ISSUE THREAD

**Issue by dneto0** [google/bigwheels#5]
These are unimplemented, but would be useful for compute shader experiments.

DX12: https://github.com/google/bigwheels/blob/main/src/ppx/grfx/dx12/dx12_descriptor.cpp#L315 

DX11: https://github.com/google/bigwheels/blob/main/src/ppx/grfx/dx11/dx11_descriptor.cpp#L260

**Comment by dneto0** [comment]
I did some prototyping with this some while ago, but didn't finish the work.

**Comment by vettoreldaniele** [comment]
Thanks for the suggestion! Looking at it, it sounds like it should be a fairly easy addition. In DX12, it's a call to [`CreateUnorderedAccessView`](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createunorderedaccessview).

**Comment by dneto0** [comment]
My work in progress on the DX12 side had this partial change:

             case grfx::DESCRIPTOR_TYPE_STORAGE_BUFFER: {
+                uint64_t sizeInBytes = (srcWrite.bufferRange == PPX_WHOLE_SIZE) ? srcWrite.pBuffer->GetSize() : srcWrite.bufferRange;
+
+                D3D12_UNORDERED_ACCESS_VIEW_DESC desc  = {};
+                // Assume a byte-addressable buffer:
+                //    desc.Format = DXGI_FORMAT_R32_TYPELESS
+                //    desc.Buffer.Flags = D3D12_BUFFER_UAV_FLAG_RAW
+                desc.Format                          = DXGI_FORMAT_R32_TYPELESS;
+                desc.ViewDimension                   = D3D12_UAV_DIMENSION_BUFFER;
+                desc.Buffer.FirstElement             = srcWrite.bufferOffset;
+                desc.Buffer.NumElements              = sizeInBytes;
+                desc.Buffer.StructureByteStride      = 0;
+                desc.Buffer.CounterOffsetInBytes     = 0;
+                desc.Buffer.Flags                    = D3D12_BUFFER_UAV_FLAG_RAW;
+
+                SIZE_T                      ptr    = heapOffset.descriptorHandle.ptr + static_cast<SIZE_T>(handleIncSizeCBVSRVUAV * srcWrite.arrayIndex);
+                D3D12_CPU_DESCRIPTOR_HANDLE handle = D3D12_CPU_DESCRIPTOR_HANDLE{ptr};
+
+                device->CreateUnorderedAccessView(ToApi(srcWrite.pBuffer)->GetDxResource(), nullptr, &desc, handle);

and the shader change was needed if I recall correctly:

--- a/assets/benchmarks/shaders/ComputeBufferIncrement.hlsl
+++ b/assets/benchmarks/shaders/ComputeBufferIncrement.hlsl
@@ -1,4 +1,4 @@
-RWByteAddressBuffer buf : register(u0, space0);
+RWStructuredBuffer<uint> buf : register(u0);

**Comment by vettoreldaniele** [comment]
This is made harder by the fact that the application expects to be able to upload data to the buffer from the CPU, which is not possible in D3D12. Some rework around buffer uploading capabilities/expectations is in order to make sure applications understand what is and what is not possible.
