### ISSUE TITLE
How to specify that the discrete gpu is selected?

### ISSUE THREAD

**Issue by warzes** [google/bigwheels#510]
As I understand it, the library takes the first gpu. But on laptops, the first video card is always the integrated gpu.

How can I force it to select the discrete gpu?

example in the screenshots
![scree](https://github.com/user-attachments/assets/33b9cfa5-8a77-4c6f-8b4b-3da5b1942627)

**Comment by jorgeag-google** [comment]
We have speciffic command line option to force a [GPU selection](https://github.com/google/bigwheels/blob/595e8f857cfff208f0b8dc62f18f63d12babca66/src/ppx/application.cpp#L597)
The caviat of course is that you need to know which index does the discrete GPU have. This is platform dependant.
So for every new enviroment (laptop, desktop in your case), you need to run any BW program with the `--list-gpus` option, that will print the available GPU witrh their corresponding indices. Note which one is the discrtete GPU.
Now that know the index of the GPU you want to use, every time you run a program you pass the CLI option with the desired index. For example if the discreate GPU happens to be on index 1, it should be `--gpu 1`
