### ISSUE TITLE
android: allow reusing Android files for multiple samples

### ISSUE THREAD

**Issue by Keenuts** [google/bigwheels#80]
Right now, the chosen sample is hard-coded in the manifest. We should find a way to reuse those. Probably with a manifest template, generating the real manifest at build time.
Or maybe we should pack all samples in one APK and have a way to select the one we start (each sample being an activity entrypoint?)

**Comment by at-ninja** [comment]
This should be doable with [build variants](https://developer.android.com/build/build-variants) to allow choosing a project from the command line or Android Studio. I'm happy to take this issue.

**Comment by Keenuts** [comment]
Just so you know, I'm working on a PR to cleanup the android build, which will change it quite a lot. If everything goes well, the manifest will have en entry to determine the build.
So should be fine with build variant, just don't invest too much time right now?

**Comment by Keenuts** [comment]
@at-ninja while cleaning up the android build, I found a way to not hardcode the library name in the MainActivity and manifest, thanks to your suggestion.
So seems like what will be needed it create multiple build variants.
And maybe tweak the build so we don't embedded all the .so in the APK, but only the one we load.

**Comment by Keenuts** [comment]
> Just a high level comment. For Android, each sample application should target its own APK and be separately debuggable from the IDE.

Yes, that's what I intend to have. What I meant by not hardcoding is not to have 1 manifest by app in the repo. But of course, once compiled, we get 1 sample per APK.

**Comment by apazylbe** [comment]
@Keenuts is this fixed with https://github.com/google/bigwheels/pull/101 ?

**Comment by Keenuts** [comment]
Yes, thanks, forgot to close!
